version: "3"

services:

    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
          - 3306:3306
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD:
          MYSQL_DATABASE: playcards
        volumes:
          - database_data:/var/lib/mysql/data

    restapi:
      build: .
      command: >
        sh -c "
        uvicorn main:app --reload"
      volumes:
        - .:/workspacefastapi
      ports:
        - "8000:8000"
      depends_on:
        - database

